[profile.default]
src = "foundry/src"
test = "foundry/test"
out = "foundry/out"
script = "foundry/script"
cache_path = "foundry/cache"
broadcast = "foundry/broadcast"
libs = ["foundry/lib"]
solc = "0.8.20"

[fmt]
single_line_statement_blocks = "single"
override_spacing = false
line_length = 150


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
