[profile.default]
src = "foundry/src"
test = "foundry/test"
out = "foundry/out"
cache_path = "foundry/cache"
libs = ["foundry/lib"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
